### ISSUE TITLE
Webhook file matching should use renovate fileMatch

### ISSUE THREAD

**Issue by rarkins** [mend/renovate-ce-ee#106]
When receiving "push" webhooks, Renovate looks at the filenames changed to determine if they are important or not. e.g. `renovate.json` or `package.json` are important. However, Renovate's list of managers has grown substantially and the list provisioned here has not kept up. Instead, the webhook receiver should build its list of patterns dynamically from the default `fileMatch` patterns in Renovate managers.

**Comment by nayrwex** [comment]
@rarkins Could I check on the status of this feature request?

**Comment by rarkins** [comment]
If you are a paying WhiteSource customer then you can contact support to express your interest in it. But otherwise no, you can't check on the status of any feature request in this product apart from waiting for an issue to be resolved.

**Comment by rarkins** [comment]
Implemented in v6
