### ISSUE TITLE
Horizontal scaling via hashed repository name?

### ISSUE THREAD

**Issue by TobiX** [mend/renovate-ce-ee#195]
Hi,

in https://github.com/whitesource/renovate-on-prem/blob/main/docs/advanced.md#horizontal-scaling you suggest:

> Feature requests about how to make the above more manageable are welcome in this repo.

I would suggest something like the following:

- Every instance of Renovate-on-Prem gets configured with a nodeId (0 <= nodeId < nodeCount) and a nodeCount
- When deciding if a node is "responsible" for a repository, it uses this algorithm:
  1. Hash something unique per repository (repository name or repository URL would probably work) with a cryptographic hash function (SHA256 for example)
  2. Accept a repository if `hash % nodeCount == nodeId`

This should create a "balanced" distribution of repositories to nodes and frees the admin from manually "sorting" repositories by name...

**Comment by rarkins** [comment]
Horizontal scaling is supported via Renovate Enterprise Edition
