### ISSUE TITLE
Is it possible to limit the cache size?

### ISSUE THREAD

**Issue by natan-abolafya** [mend/renovate-ce-ee#197]
It seems to fill pretty fast in our environment. Probably due to schedule being rather frequent. Regardless fast or slow though, this causes headaches where the disk is limited.

This is after 3 days
```
du -h --max-depth=1 /tmp/renovate
5.6G    /tmp/renovate/cache
88M     /tmp/renovate/github
5.7G    /tmp/renovate
```

I suppose there may be external ways to clear the cache like a cronjob deleting the directory weekly but perhaps there is a more efficient way for renovate to manage that? Searching through `cache` in documentation wasn't fruitful.

**Comment by TobiX** [comment]
Related issue: https://github.com/renovatebot/renovate/issues/13732

**Comment by rarkins** [comment]
What's consuming the most in cache? Isn't 5GB pretty manageable in 2022? Is it really better if you continuously prune the cache then soon after re-download the same before repeating?

**Comment by natan-abolafya** [comment]
5GB is manageable but it doesn't stop there. Right now it's 7.3GB. It was about 70GB the other day and took down the system as the disk size was pretty small on the machine because we didn't expect this. 

> What's consuming the most in cache? 

It's hard to tell for me. It's these each taking about 20-30MB.

```
/tmp/renovate/cache/renovate/renovate/renovate-cache-v1/content-v2/sha512# ls
00  05  0a  0f  14  19  1e  23  28  2d  32  37  3c  41  46  4b  50  55  5a  5f  64  69  6e  73  78  7d  82  87  8c  91  96  9b  a0  a5  aa  af  b4  b9  be  c3  c8  cd  d2  d7  dc  e1  e6  eb  f0  f5  fa  ff
01  06  0b  10  15  1a  1f  24  29  2e  33  38  3d  42  47  4c  51  56  5b  60  65  6a  6f  74  79  7e  83  88  8d  92  97  9c  a1  a6  ab  b0  b5  ba  bf  c4  c9  ce  d3  d8  dd  e2  e7  ec  f1  f6  fb
02  07  0c  11  16  1b  20  25  2a  2f  34  39  3e  43  48  4d  52  57  5c  61  66  6b  70  75  7a  7f  84  89  8e  93  98  9d  a2  a7  ac  b1  b6  bb  c0  c5  ca  cf  d4  d9  de  e3  e8  ed  f2  f7  fc
03  08  0d  12  17  1c  21  26  2b  30  35  3a  3f  44  49  4e  53  58  5d  62  67  6c  71  76  7b  80  85  8a  8f  94  99  9e  a3  a8  ad  b2  b7  bc  c1  c6  cb  d0  d5  da  df  e4  e9  ee  f3  f8  fd
04  09  0e  13  18  1d  22  27  2c  31  36  3b  40  45  4a  4f  54  59  5e  63  68  6d  72  77  7c  81  86  8b  90  95  9a  9f  a4  a9  ae  b3  b8  bd  c2  c7  cc  d1  d6  db  e0  e5  ea  ef  f4  f9  fe
```

**Comment by rarkins** [comment]
So that's renovate's internal package cache. Same issue/solution as linked above (ie needs solution in OSS repo first)

**Comment by bizrad** [comment]
@rarkins In #13732 I mentioned possibility running a find command to clean up the cache as another possible workaround for this. Would it be reasonable to run `find /renovate/cache -type f -mtime +90 -delete` or would that cause issues with how the cache works?

**Comment by rarkins** [comment]
The cache uses `cacache` and I'm not sure if any of that is safe or if it would corrupt it. I think we might want to:
1. Add automatic pruning capability to Renovate (maybe with an option to disable if really necessary)
2. Release it in a major release of Renovate OSS and On-Prem, warning people to manually remove their existing cache before upgrading because pruning could take a very long time

An alternative to (2) could be that we change cache filename/location and `rm -rf` the old cache filename if found, but I'm not sure if that's a good idea.

**Comment by nabeelsaabna** [comment]
cache cleanup is already handled by Renovate OSS

**Comment by natan-abolafya** [comment]
This is great @nabeelsaabna! Does it require some configuration or is it something renovate handles by itself?
