### ISSUE TITLE
Pushing a modification for renovate.json5 shows the log 'Ignoring unimportant commits to master'

### ISSUE THREAD

**Issue by bc-lee** [mend/renovate-ce-ee#201]
However, if I modify `renovate.json`, these logs are not shown and enqueue the target repository.

It would be nice to treat `renovate.json5` as equivalent to `renovate.json`.

**Comment by Mistic92** [comment]
I'm getting this error message for all events from Gitlab, every commit is marked as unimportant and ignored.

**Comment by rarkins** [comment]
It is expected that the majority of commit events are ignored. If you find it ignored for `renovate.json` or `package.json` then it indicates a problem
