### ISSUE TITLE
Mark "unhealthy" when queue makes no progress for a long time

### ISSUE THREAD

**Issue by TobiX** [mend/renovate-ce-ee#265]
Currently, both liveness and readiness probes point to /, which just returns `status: "OK"` when the server is running. It would be nice if the server could detect "problematic" states and reflect that, so it can be restarted by k8s, for example.

This came up because we ran into a problem, where the queue got "stuck", but the server just kept running and didn't handle any request anymore. This could be observed from the `/status` endpoint:

```json
{
  "status": {
    "bootDate": "2023-03-24T13:42:23.640Z",
    "scheduler": {
      "platform": "gitlab",
      "cron": "0 */2 * * *",
      "lastScheduling": "2023-03-29T10:00:00.007Z"
    },
    "webhooks": {
      "lastWebhookReceived": "2023-03-29T10:25:54.120Z"
    },
    "jobs": {
      "lastEnqueueDate": "2023-03-29T10:18:25.289Z",
      "lastJobDispatchDate": "2023-03-26T23:49:24.423Z",
      "lastJob": {
        "reason": "scheduled",
        "repository": "repoA",
        "priority": 100,
        "logContext": "Ryqmcv2_T",
        "params": {}
      },
      "lastJobFinished": {
        "reason": "scheduled",
        "repository": "repoB",
        "priority": 100,
        "logContext": "Ryqmcv2_T",
        "params": {},
        "finished": "2023-03-26T23:49:24.422Z"
      },
      "queueLength": 666,
      "totalJobsProcessed": 10920
    },
    "jobsInProgress": [
      {
        "repository": "repoA",
        "started": "2023-03-26T23:49:24.423Z"
      }
    ],
    "worker": {
      "remediateServerEnabled": false,
      "previousJob": {
        "reason": "scheduled",
        "repository": "repoB",
        "priority": 100,
        "logContext": "Ryqmcv2_T",
        "params": {}
      },
      "previousJobStart": "2023-03-26T23:48:56.219Z",
      "currentJob": {
        "reason": "scheduled",
        "repository": "repoA",
        "priority": 100,
        "logContext": "Ryqmcv2_T",
        "params": {}
      },
      "currentJobStart": "2023-03-26T23:49:24.423Z"
    }
  }
}
```

The "fix" for this situation was to just restart the deployment, but this could have been automated if a health check for this state existed...

**Comment by rarkins** [comment]
So in such a case, what should be the response from `/`? e.g. 4xx, 5xx, or 2xx with a particular body?

And would it help if the container restarted _itself_? We might make it configurable to be:
- none (current)
- reflect in status (what you're asking)
- reboot self (more automated, but may not suit every environment)

**Comment by TobiX** [comment]
The "standard" with k8s is indeed just a different HTTP code. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request says:

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

Implementing something like that would line up with the current default configuration in the Helm chart (https://github.com/mend/renovate-on-prem/blob/main/helm-charts/whitesource-renovate/values.yaml#L139-L147).

**Comment by nabeelsaabna** [comment]
Hi @TobiX 
Is this still relevant ?

**Comment by TobiX** [comment]
Just happened again, but we haven't switched from Renovate-on-Prem to Renovate CE yet...

**Comment by TobiX** [comment]
I haven't seen the issue again with Renovate CE
