### ISSUE TITLE
Configuration breaks when GITHUB_COM_TOKEN is not set.

### ISSUE THREAD

**Issue by mdaniline** [mend/renovate-ce-ee#290]
Hello

I am running Renovatebot using GHE. Our environment is closed off to the Internet, which means that I cannot use anything that communicates directly with Github, and hence have no need to set `GITHUB_COM_TOKEN`.

However, the code in `server,js` seems to break the configuration in certain cases.

**Steps to reproduce**

* Set up an `ORG/renovate-config` repo with `default.js` file.
```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
        "config:base",
        ":rebaseStalePrs"
    ],
    "ignorePresets": [
        ":dependencyDashboard",
        "workarounds:javaLTSVersions"
    ],
    "enabledManagers": [
        "gradle"
    ],
    "packageRules": [
        {
            "description":"Disable managers to avoid external requests",
            "matchDatasources": [
                "gradle-version",
                "java-version"
            ],
            "enabled": false
        }
    ]
}
````
* Install Renovatebot on all repos in `ORG` (to make life simpler)
* Deploy the on-prem app (in my case via Helm).
* Create a new repo
* Wait for Renovatebot to try and register the repo.

**Expected result**

The repository is registered

**Actual** result**

The following in the logs:
```
DEBUG: Using file match: [object Object] for manager gradle (repository=ORG/REPO)
INFO: Repository has invalid config (repository=ORG/REPO)
       "error": {
         "validationSource": "[object Object]",
         "validationError": "Invalid regular expression: [object Object]",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at regEx (/usr/src/app/node_modules/renovate/dist/util/regex.js:47:23)\n    at getMatchingFiles (/usr/src/app/node_modules/renovate/dist/workers/repository/extract/file-match.js:37:38)\n    at tryConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/extract/index.js:22:68)\n    at extractAllDependencies (/usr/src/app/node_modules/renovate/dist/workers/repository/extract/in
dex.js:36:13)\n    at async checkOnboardingBranch (/usr/src/app/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:58:29)\n    at async getRepoConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/init/config.js:10:14)\n    at async initRepo (/usr/src/app/node_modules/renovate/dist/workers/repository/init/index.js:38:14)\n    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:46:18
)\n    at async q (/usr/src/app/src/server.js:1:44965)\n    at async startWorker (/usr/src/app/src/server.js:1:46080)"
       }
```

**What is going on**

It appears that whenever `server.js` is started, the following block is added to `packageRules` whenever `GITHUB_COM_TOKEN` is not set:
```
{ description: "Disable managers to avoid github.com requests and rate limiting", matchDatasources: ["github-tags", "github-releases", "go"], enabled: false }
```
The problem is that this block then ends up in a variety of configuration blocks where it absolutely does not belong. Critically, it ends up in the `fileMatch` block:

```
"fileMatch": [
    {
      "description": "Disable managers to avoid github.com requests and rate limiting",
      "matchDatasources": [
        "github-tags",
        "github-releases",
        "go"
      ],
      "enabled": false
    },
    "\\.gradle(\\.kts)?$",
    "(^|/)gradle\\.properties$",
    "(^|/)gradle/.+\\.toml$",
    "(^|/)buildSrc/.+\\.kt$",
    "\\.versions\\.toml$",
    "(^|/)versions.props$",
    "(^|/)versions.lock$"
  ],
```
This then causes the error in the logs - the `[object Object]` is actually this 'Disable managers` object.

In `server.js`, the problem appears to be this minified code:

```
t.packageRules=e.packageRules||[],t.packageRules.push({description:"Disable managers to avoid github.com requests and rate limiting",matchDatasources:["github-tags","github-releases","go"],enabled:!1})
```

In particular, `e.packageRules` seems reference an object in various places in the config. I suspect the default empty array is a single reference, which is why so many array-valued config values end up with this new block (similar to [this python gotcha](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) maybe? )

**Solution**

I found that running the following Dockerimage _seems_ to fix the issue:
```
FROM whitesource/renovate:4.2.0

# Internal cert setup etc

RUN sed -i 's/t\.packageRules=e\.packageRules||\[]/t\.packageRules=e\.packageRules?\[\.\.\.e\.packageRules]:\[]/g' /usr/src/app/src/server.js
```

All this does is replace `t.packageRules=e.packageRules||[]` in `server.js` with `t.packageRules=e.packageRules?[...e.packageRules]:[]`, i.e. create a shallow clone of `e.packageRules` if it exists, instead of using it directly.

Obviously this is a horrible, fragile hack, so would be much appreciated if this was fixed properly in the code :)  While it would be fine to fix it in the on-prem server implementation, I suspect the actual problem is the sharing of the empty list reference, which is probably somewhere in [renovatebot/renovate](https://github.com/renovatebot/renovate)

**Comment by mdaniline** [comment]
Raised https://github.com/renovatebot/renovate/pull/22587, which *may* solve the problem.

**Comment by nabeelsaabna** [comment]
Hi @mdaniline,
thanks for the [PR](https://github.com/renovatebot/renovate/pull/22587) and deep investigation of the issue,
It was also temporary fixed by doing deep copy in `server.js` and will part of next release.
