### ISSUE TITLE
Which Mend Renovate Community Edition Docker image should I be using?

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#324]
I notice that we [now have two images](https://github.com/orgs/mend/packages/container/package/renovate-ce0) - `6.0.0` and `6.0.0-full`.

I assume that the `-full` image contains pre-installed tools, whereas the non`-full` image will download as and needed? But would be good to know for sure!

**Comment by nabeelsaabna** [comment]
the `6.0.0-full` is more useful in cases where the user does not have "free access to the internet" and can't install tools at runtime

**Comment by rarkins** [comment]
It's now the same approach as renovate CLI images. Use -full if you want every tool preinstalled as on-prem used to have

**Comment by rarkins** [comment]
Fixed by https://github.com/mend/renovate-ce-ee/commit/b59be8941d98dfc2c8e9b8c9f8ba2b26042b34c8
