### ISSUE TITLE
Outdated helm chart

### ISSUE THREAD

**Issue by paymand** [mend/renovate-ce-ee#326]
Are there any plans to update the helm chart?

The values do not map to the new variables. For example:
https://github.com/mend/renovate-ce-ee/blob/main/helm-charts/whitesource-renovate/templates/deployment.yaml#L41-L42
`acceptWhiteSourceTos` maps to `ACCEPT_WHITESOURCE_TOS` while it should be mapped to `MEND_RNV_ACCEPT_TOS`.

Same for the secrets: https://github.com/mend/renovate-ce-ee/blob/main/helm-charts/whitesource-renovate/templates/deployment.yaml#L46

We have just finished configuring our [self-hosted setup](https://github.com/mend/renovate-ce-ee/issues/317) using the `whitesource-renovate` chart and looks like switching to the new Renovate CE is gonna be quite a bit of work for people using the previous helm chart.

**Comment by rarkins** [comment]
The helm chart will be updated next week.

**Comment by paymand** [comment]
Updated here: https://github.com/mend/renovate-ce-ee/pull/349
