### ISSUE TITLE
Renovate CE now sets onboarding PRs/MRs by default

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#327]
I've noticed that as part of starting up, my logs noted several cases where we are now sending onboarding PRs to repos:

```
 INFO: Repository started (repository=tanna.dev/editor.tanna.dev)
       "renovateVersion": "37.0.0"
 INFO: Branch created (repository=tanna.dev/editor.tanna.dev, branch=renovate/configure)
       "commit": "854f94593120e82e73eae33317351d8c64030b3c",
       "onboarding": true
 INFO: Dependency extraction complete (repository=tanna.dev/editor.tanna.dev, baseBranch=main)
       "stats": {                                 
         "managers": {                            
           "gitlabci": {"fileCount": 1, "depCount": 1},
           "npm": {"fileCount": 1, "depCount": 7}
         },                                       
         "total": {"fileCount": 2, "depCount": 8}
       }                                          
 INFO: Onboarding PR created (repository=tanna.dev/editor.tanna.dev)
       "pr": "Pull Request #1"
```

Looking at the environment variables for the running application, there appears to be a new default onboarding configuration:

```sh
RENOVATE_ONBOARDING_CONFIG={"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["config:recommended"]}
```

This leads possibly unexpected behaviour compared to previous setups.

Or is it maybe just that Renovate 37.0.0 now performs onboarding PRs/MRs by default?

**Comment by rarkins** [comment]
Renovate itself has always onboarded repos by default. I don't think on-prem ever changed that default either. 

I think it's important that you also get debug logging working as info level are almost never sufficient

**Comment by jamietanna** [comment]
Sorry, this turns out to be 100% user error :sweat_smile: I recently migrated from a GitLab CI based renovate-runner, which had the `RENOVATE_EXTRA_FLAGS=--onboarding false` set, but I didn't migrate that over when I moved to Renovate On Prem, but only noticed it as part of the migration to Mend Renovate Community Edition.

Apologies for the time wasting!
