### ISSUE TITLE
Opening a shell with Renovate CE results in `sh: 3: Syntax error: "(" unexpected`

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#329]
It may be benign, as a shell can still be used OK, but there may be some setup or config that's not being applied.

I see:

```
ubuntu@3fd552c50fa2:/usr/src/app$ sh -x
+ export CONTAINERBASE=1 USER_NAME=ubuntu USER_ID=1000 USER_HOME=/home/ubuntu CONTAINERBASE_ENV=1
sh: 3: Syntax error: "(" unexpected
$ 
```

**Comment by nabeelsaabna** [comment]
this issue might better moved to https://github.com/containerbase/base/
the image is based on: `ghcr.io/containerbase/base:9.10.4`

**Comment by jamietanna** [comment]
That sounds like a plan, I can see the issue is the same with that image:

```
% docker run -ti ghcr.io/containerbase/base:9.10.4 sh -x
+ export CONTAINERBASE=1 USER_NAME=ubuntu USER_ID=1000 USER_HOME=/home/ubuntu CONTAINERBASE_ENV=1
sh: 3: Syntax error: "(" unexpected
```

Are you able to transfer this issue?

**Comment by rarkins** [comment]
Unfortunately cannot transfer across different orgs
