### ISSUE TITLE
License required for Renovate CE?

### ISSUE THREAD

**Issue by szpak** [mend/renovate-ce-ee#331]
There is in README:

> Use of Mend Renovate On-Premises is bound by [Mend's Terms of Service](https://www.mend.io/terms-of-service/). You can request a license key by submitting the form at https://www.mend.io/free-developer-tools/renovate/on-premises/. License requests are processed semi-manually so please allow up to 3 working days to receive your license key by email.

I wonder, if it is a leftover (as `Mend Renovate On-Premises` is used) or Renovate CE still requires a license key?

**Comment by rarkins** [comment]
Nothing has changed license-wise - one is still required (free). I updated the old text - thanks
