### ISSUE TITLE
K8S healthcheck failing

### ISSUE THREAD

**Issue by enricojonas** [mend/renovate-ce-ee#338]
I have tried to upgrade from v5.0.0 to v6.0.0 docker image according to the instructions (e.g. renamed variables). It seems the server is starting up correctly and I can see

```
"Server listening on port 8080"
```

However, K8S (GKE in our case) restarts the pod as the healthcheck is failing. Probes are configured against "/" on port 8080, just as before.

One weird thing I noticed is that it tries to process repositories right after the server has started. 5.0.0 did not do this and was only doing on it webhook event or as per schedule. Maybe it's two different issues though.

Have rolled back to v5.0.0 without problems for now.

**Comment by rarkins** [comment]
Can you check if the `/health` endpoint works for you in v6?

**Comment by rarkins** [comment]
And can you clarify: your expectation is that `/` answers with a simple 200 OK?

**Comment by enricojonas** [comment]
@rarkins yes, /health seems to do the trick. We can use this. 200 yes.

However, still after server is started some initial run seems to kick off for all repos:

```
"Server listening on port 8080"
"Running Renovate job"
"Executing Renovate run command"
--> reason: "hourly"
```

Despite the configuration:

```
MEND_RNV_CRON_JOB_SCHEDULER = "0 5 * * *"
"Starting scheduler" - cronTime: "0 5 * * *"
```

I am sure this did not happen before - it was just running according to schedule or on incoming webhook.

I just tried to trigger a re-run from the dependency dashboard but it seems the webhook is not handled - cannot see anything in the logs basically for any incoming webhook. Maybe I am missing something - the configuration seems correct. The github app (GHES) is configured to "renovate-url/webhook". Webhooks cannot be delivered. There was no change anywhere else - just updated the variable names accordingly and used the new Docker image.

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by rarkins** [comment]
Please ensure you have set `MEND_RNV_WEBHOOK_SECRET=renovate` as unfortunately there's a bug where it is _not_ defaulting to `renovate` (this will be fixed soon). If you haven't done this then it could explain why webhooks are rejected. BTW we will make such rejections more graceful too! Cc @Gabriel-Ladzaretti

**Comment by enricojonas** [comment]
@rarkins but we have configured a different secret for this and I am setting this variable already with the actual secret...

**Comment by rarkins** [comment]
OK, so that's not it then. I will close this issue, because the original topic is resolved and I have added to the migration docs: https://github.com/mend/renovate-ce-ee/blob/main/docs/migrating-to-renovate-ce.md

Please start a _Discussion_ (not Issue) per topic for remaining topics. I will convert them to issues if they are indeed a bug which needs fixing

**Comment by enricojonas** [comment]
@rarkins for the webhook the loadbalancer also needed the updated healthcheck - so all fine. For the other issue I have created a discussion. Thanks!
