### ISSUE TITLE
Documentation: AppSync Cron

### ISSUE THREAD

**Issue by Reamer** [mend/renovate-ce-ee#350]
I am currently migrating from Renovate 5.x to 6.x and came across the following new configuration parameter. What does the cron `MEND_RNV_CRON_APP_SYNC` do?
I want to evaluate how to optimize the instance to my infrastructure.

What is an `APP` in Renovate context?

**Comment by morremeyer** [comment]
Thanks for the info @PhilipAbed. What exactly does this synchronization achieve? Why is there a persistent database at all? So far, state has been only in the PRs of the renovated repositories.

I'm aware of the sqlite to persist the queue, but this does sound unrelated to repositories/owners being synchronized.

**Comment by rarkins** [comment]
Sync is essentially autodiscover, but it's decoupled from the regular scheduled cron because it's overkill to autodiscover/sync every time. In theory the app sync would only pick up changes of significance if we had a bug or missed webhooks

**Comment by Reamer** [comment]
Thank you for the explanation. Does it make sense to write this down in the documentation?

**Comment by rarkins** [comment]
Yes

**Comment by Reamer** [comment]
> Yes

I will prepare a PR.
