### ISSUE TITLE
Renovate PRs for Renovate CE showing wrong source URL

### ISSUE THREAD

**Issue by colinodell** [mend/renovate-ce-ee#365]
Our Renovate CE instance tries to keep itself updated by opening a new PR whenever a newer `ghcr.io/mend/renovate-ce` image is available.  However, the source URL linked in the PR is for https://github.com/containerbase/base whereas I expected it to be https://github.com/mend/renovate-ce-ee.

This happens because Renovate's `docker` datasource uses the value of the label `org.opencontainers.image.source` and `org.label-schema.vcs-url` as the `sourceUrl` ([docs](https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md)) and this is what the Renovate CE image has:

```
$ docker inspect ghcr.io/mend/renovate-ce:6.2.0-full --format='{{json .Config.Labels}}' | jq

{
  "maintainer": "Rhys Arkins <rhys@arkins.net>",
  "org.opencontainers.image.ref.name": "ubuntu",
  "org.opencontainers.image.source": "https://github.com/containerbase/base",
  "org.opencontainers.image.version": "9.20.8"
}
```

**Would it be possible to overwrite that label with `https://github.com/mend/renovate-ce-ee` so PRs link to the expected place?**. This would make it easier for me to quickly access the release notes for the new image.

----

Alternatively...

The OCI Image Format Spec says that `org.opencontainers.image.source` should contain the "URL to get source code for building the image", but the underlying source for Renovate CE isn't published. So maybe it would be better to:

1. Remove `org.opencontainers.image.source` from this image
2. Set `org.opencontainers.image.url` instead, which can be any "URL to find more information on the image"
3. Add support for this label to Renovate's `docker` datasource as the `homepage` (or `sourceUrl` fallback if `.image.source` is missing)

If you prefer that approach I'd be happy to contribute ⌗3 - just let me know!

**Comment by colinodell** [comment]
See PR #364 for an example of the unexpected link

**Comment by PhilipAbed** [comment]
Hi @colinodell,

sure,
We will change the labels as you suggested.

**Comment by Gabriel-Ladzaretti** [comment]
addressed in `v6.6.0`.

**Comment by PhilipAbed** [comment]
Hi @colinodell
can you do the  fallback to img.url instead of source.url in renovate opensource?

**Comment by colinodell** [comment]
Thanks! Yes, I will open a PR to contribute that to Renovate open-source :)

**Comment by nabeelsaabna** [comment]
fixed 👍 
check https://github.com/mend/renovate-ce-ee/pull/412 for example
