### ISSUE TITLE
MEND_RNV_AUTODISCOVER_FILTER not working

### ISSUE THREAD

**Issue by dctrwatson** [mend/renovate-ce-ee#370]
I tried adding comma separated list to this env var, it seems to both enable filtering but still ignores any tasks/events for repos in the list.

When renovate ce started up, it logged `"msg":"Deleting repositories"` for all the repos in the list. No tasks were queued for them on startup either.

If I tried to manually trigger a run via the Dependency Dashboard, it would see the event and then just log `"Task does not require model updating"`

Version: 6.3.0
Platform: github

**Comment by Gabriel-Ladzaretti** [comment]
The list of deleted repositories is basically composed of the repositories that didn't match any filters. therefore, they are not part of the database, and no job will be triggered for them.

You can check the entire resolved configuration at startup, search for "Resolved configuration". 
I suggest maybe validating your filters to ensure they are set up correctly.
`MEND_RNV_AUTODISCOVER_FILTER` accepts the same (regex/minimatch) values as `RENOVATE_AUTODISCOVER_FILTER` does - https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter

**Comment by dctrwatson** [comment]
I see the issue now... Missed this the first skim through. The list is being parsed with leading spaces include.
`org/foo, org/bar` -> `["org/foo", " org/bar"]`

Would it be possible that when `MEND_RNV_AUTODISCOVER_FILTER` is parsed to `trim()` each item?

**Comment by Gabriel-Ladzaretti** [comment]
I just checked, and you are right. The current release doesn't use `trim()` when parsing the filter. however, the environment handling was refactored quite heavily, and this is no longer the case. so, until we release it, see if you can remove the whitespace from the value you set.

**Comment by rarkins** [comment]
Let's ensure behavior is consistent with the renovate CLI

**Comment by Gabriel-Ladzaretti** [comment]
fixed by release 6.4.0

**Comment by michael-mader** [comment]
release 6.4.0 caused servere issues on our side as the MEND_RNV_AUTODISCOVER_FILTER environment variable causes renovate to ignore the autodiscoverFilter set in config even if it is not set explicitly.

Moving our autodisoverFilter string ("group/subgroup/**") from config to the env value (via helm) fixed the issue.
Unfortunately this is not mentioned anywhere in the changelog

**Comment by Gabriel-Ladzaretti** [comment]
You are correct. 
Only the server side auto discover filter should be used.
sorry for the inconvenience. 
The docs will be updated to reflect this.

**Comment by rarkins** [comment]
can we fall back to supportingt `RENOVATE_AUTODISCOVER` and log a warning?

**Comment by nabeelsaabna** [comment]
Don't think it's needed at this point because there was ~2 weeks between releasing `MEND_RNV_AUTODISCOVER_FILTER` and between disabling `RENOVATE_AUTODISCOVER`
WDYT ?

**Comment by rarkins** [comment]
The request was to fall back to the renovate oss env for this in case people made a mistake

**Comment by Gabriel-Ladzaretti** [comment]
Just note that this fallback won't work for users who use a `config.js` file.
