### ISSUE TITLE
Published docker image points to invalid source repository

### ISSUE THREAD

**Issue by lluiscab** [mend/renovate-ce-ee#386]
The published docker image seems to have it's source repository set to https://github.com/containerbase/base instead of https://github.com/mend/renovate-ce-ee/. This causes renovate itself to incorrectly fetch release logs.

The changelog that's loaded for v6.5.0 by renovate itself is actually the changelog of the `v6.5.0` release of `containerbase/base` (https://github.com/containerbase/base/releases/tag/6.5.0) instead of the expected:
![image](https://github.com/mend/renovate-ce-ee/assets/7149212/e229be5f-39d8-4fcf-bbcc-6b58f24f5a39)

Real v6.5.0 changelog from this repository
![image](https://github.com/mend/renovate-ce-ee/assets/7149212/eeda499d-1317-47a8-bb8c-df6e648ec480)

**Comment by Gabriel-Ladzaretti** [comment]
Thank you for the detailed issue report. It is currently being addressed and will be fixed soon.

It seems to be related to:
- https://github.com/mend/renovate-ce-ee/issues/365

**Comment by Gabriel-Ladzaretti** [comment]
addressed in `v6.6.0`.

**Comment by lluiscab** [comment]
Seems like there's no changelog available now
![image](https://github.com/mend/renovate-ce-ee/assets/7149212/8f56501c-c2ba-40d9-9c61-86e48f984604)

Could it be because `org.opencontainers.image.version` is empty and removate tries to fetch a changelog for release `6.6.0-full` instead of `6.6.0`?

```sh
$ docker inspect ghcr.io/mend/renovate-ce:6.6.0-full --format='{{json .Config.Labels}}' | jq

{
  "maintainer": "Mend.io",
  "org.opencontainers.image.ref.name": "ubuntu",
  "org.opencontainers.image.source": "",
  "org.opencontainers.image.url": "https://github.com/mend/renovate-ce-ee",
  "org.opencontainers.image.version": ""
}
```

**Comment by PhilipAbed** [comment]
It was pending this fix https://github.com/renovatebot/renovate/pull/25882
we will need to pump up `renovate` version as well inside `renovate-ce-ee` to support this.

**Comment by nabeelsaabna** [comment]
issue fixed
