### ISSUE TITLE
Manual enqueuing of repository

### ISSUE THREAD

**Issue by rarkins** [mend/renovate-ce-ee#4]
Support a CLI command to add a repository to the job queue with high priority. i.e. "Renovate repository x now".

**Comment by baurmatt** [comment]
As you've specially mention a CLI command: Is there already a way of doing this through API/similar?

**Comment by rarkins** [comment]
I'm not sure why I suggested CLI actually, because these days I'd prefer an API first too.

**Comment by baurmatt** [comment]
Hey @rarkins, any chance to get this implemented? :)
