### ISSUE TITLE
Renovate not recognizing commit author after setting platformCommit=true

### ISSUE THREAD

**Issue by lixdavid94** [mend/renovate-ce-ee#403]
Hello!

We recently migrated over from renovate-on-prem to renovate-ce, and noticed that commit signing, by setting a `gitPrivateKey` stopped working, so we switched over to setting `RENOVATE_PLATFORM_COMMIT` as `true`. This solved the commit signing issues and PRs are now being signed by the github application, but are now seeing renovate having problems rebasing PRs when renovate gets restarted. We are seeing this comment in the PRs:

![Screenshot 2023-12-04 at 4 36 21 PM](https://github.com/mend/renovate-ce-ee/assets/5509450/194208d6-42ae-4a22-af3b-164fb3ba6276)

However there is only one commit in that PR from the renovate app. 

![Screenshot 2023-12-04 at 4 36 51 PM](https://github.com/mend/renovate-ce-ee/assets/5509450/9295180e-fb3f-45a9-9974-d7db5784db44)

Any idea why renovate is having issues recognizing the previous commit author when the only commit came from renovate? We aren't persisting any data right now, although we didn't before on renovate-on-prem either and didn't have this issue when using a `gitPrivateKey`. Also when I clone the repo and checkout the branch that renovate opened, doing a `git log -n1` shows that the last commit came from renovate.

```
commit 7c20dd173d5486c4706e7cd7d512f3f32d621b92 (HEAD -> renovate/golang-bullseye)
Author: renovate-01-kbuild-dev[bot] <113736748+renovate-01-kbuild-dev[bot]@users.noreply.github.com>
Date:   Fri Dec 1 00:03:34 2023 +0000

    Update golang:bullseye Docker digest to 3b4ac76
```

**Comment by rarkins** [comment]
Hi, this topic is not specific to Renovate CE/EE, so please raise it in the regular [Renovate discussions](https://github.com/renovatebot/renovate/discussions) if you need more information after this.

The debug log messages from Renovate should let you know (a) which git author it thinks it is, and (b) which git author it thinks is someone else. You likely need to add the latter to `gitIgnoredAuthors`.
