### ISSUE TITLE
WARN: Cannot parse env: "env": "GITHUB_COM_TOKEN"

### ISSUE THREAD

**Issue by olwe0002** [mend/renovate-ce-ee#408]
In the values of the ce it is possible to [define](https://github.com/mend/renovate-ce-ee/blob/c18f79ffd7be23b4fb5f0ca73309f32c2f75a378/helm-charts/mend-renovate-ce/values.yaml#L55) the `renovate.githubComToken`, which [results](https://github.com/mend/renovate-ce-ee/blob/c18f79ffd7be23b4fb5f0ca73309f32c2f75a378/helm-charts/mend-renovate-ce/templates/deployment.yaml#L92) in the env variable `GITHUB_COM_TOKEN`.

In the running pod, there are a lots of those entries:

```
WARN: Cannot parse env
    "env": "GITHUB_COM_TOKEN"
```

seems like something is wrong here

**Comment by rarkins** [comment]
Fixed in Renovate OSS here: https://github.com/renovatebot/renovate/pull/26224

It's safe to ignore in the meantime until the next Renovate CE is released.

**Comment by nabeelsaabna** [comment]
latest release `6.8.0` is available with Renovate `v37.105.1` that includes the fix
