### ISSUE TITLE
API: Authorization header not RFC-compliant

### ISSUE THREAD

**Issue by morremeyer** [mend/renovate-ce-ee#410]
## Problem

The current API `Authorization` header format is

```
Authorization: {token}
```

However, the format specified by RFC-9110

```
Authorization: {scheme} {parameters}
```

as described by e.g. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#syntax).

This leads to problems when using standard libraries that assume that there is always a `scheme` present.
In my case, this is the prometheus `http_client_config` - I'm currently working on scraping the `/api/status` endpoint with the [json_exporter](https://github.com/prometheus-community/json_exporter/tree/master), where I need to configure the credentials.

The only way to do this with the current header format is to explicitly set the header in the json_exporter "module" configuration as shown in https://github.com/prometheus-community/json_exporter/blob/7eb4fff7f0284666a236a9f2261b623344da4cb7/examples/config.yml#L5.

## Potential Solution

With renovate-ce and -ee supporting the standard `Authorization` header format, it would be possible to load the credentials from a file since the prometheus `http_client_config` supports loading credentials for `Authorization` headers from files.

The header should be modified to be

```
Authorization: Bearer {token}
```

## References

RFC9110 specifies the [Authorization header](https://www.rfc-editor.org/rfc/rfc9110.html#field.authorization) as `Authorization = credentials` and the [credentials](https://www.rfc-editor.org/rfc/rfc9110.html#name-credentials) as `credentials = auth-scheme [ 1*SP ( token68 / #auth-param ) ]`, leading to the more human-readable notation that MDN uses and I noted above.

**Comment by rarkins** [comment]
Would it be better to use Bearer instead of Token? That's likely the default which libraries use

**Comment by morremeyer** [comment]
Good call, yes. Prometheus indeed defaults to `Bearer`, see https://github.com/prometheus/common/blob/c59927ec74c04c0c17891bf27784fe7c484ae97f/config/http_config.go#L354.
