### ISSUE TITLE
Support Gitlab groups

### ISSUE THREAD

**Issue by lazysteel93** [mend/renovate-ce-ee#415]
It would be nice if Renovate would expand a group name when parsing a CODEOWNERS file on Gitlab. According to my testing, this is not possible yet, and then I discovered it was discussed+fixed on the other renovate Github project: https://github.com/renovatebot/renovate/pull/19469/commits/87b82cfa7717559706ccac6d67bb20c166656425

Request to incorporate a similar feature in renovate-ce-ee.

**Comment by rarkins** [comment]
That version of Renovate is already part of Renovate CE. If it's not working then it needs changes in the referenced repo and not here
