### ISSUE TITLE
Allow overriding serviceAccountName in helm template

### ISSUE THREAD

**Issue by xNok** [mend/renovate-ce-ee#426]
Adding this option would allow using workload identity for access to ECR (AWS) or Container Registry (GCP)

Renovate itself seems to support this, so it is only a matter of providing a service account: https://docs.renovatebot.com/docker/#using-application-default-credentials-workload-identity-self-hosted-only

**Comment by rarkins** [comment]
Is this something you can submit a PR for? I don't understand where the change is needed

**Comment by missedone** [comment]
@xNok i had the PR for CE chart for the exactly same purpose that allow the renovate pod access the private ECR 
https://github.com/mend/renovate-ce-ee/pull/441

**Comment by xNok** [comment]
Great news since it is merged, we can close this issue!
