### ISSUE TITLE
Recursive Reviewers from Code Owners on Gitlab

### ISSUE THREAD

**Issue by lazysteel93** [mend/renovate-ce-ee#431]
When using renovate-ce `6.7.0` and self-hosted Gitlab, I am having an issue with auto assignment of reviewers. Relevant configuration is:

`RENOVATE_ASSIGNEES_FROM_CODE_OWNERS=false` and `RENOVATE_REVIEWERS_FROM_CODE_OWNERS=true` on my Renovate container.

The issue is that with a CODEOWNERS file such as:
```
* @Joe @Bob
containers/ @Sally @Jane 
```

MRs created by Renovate that only affect the `containers/` folder are assigned to: Joe, Bob, Sally, and Jane. Our desired behavior is that they'd be assigned just to Sally and Jane. Our desired behavior is for it to behave how gitlab behaves where it would be assigned just to Sally and Jane.

Please let me know if any more information needs to be provided to help with this issue.

**Comment by rarkins** [comment]
Hi, this is not related to this CE/EE repo. Please open a discussion question in the main Renovate repo. It's possible you have a variant of CODEOWNERS which renovate doesn't recognize (it's not really a standard format)
