### ISSUE TITLE
Never received a license key

### ISSUE THREAD

**Issue by robinschneider** [mend/renovate-ce-ee#455]
Hello,

We requested a license key a couple of weeks ago and never received one.
We filled out the form at the website, what else do we have to do?

**Comment by rarkins** [comment]
Best to resubmit the form. Be sure not to put any blatantly fake data into the form as that can cause it to be filtered out

**Comment by robinschneider** [comment]
I submitted the form with real data.

**Comment by rarkins** [comment]
Please submit the form again

**Comment by robinschneider** [comment]
I did so

**Comment by rarkins** [comment]
I've still not seen anything come through which looks like your name. Could you do the following?

- Fill out and submit the form one more time
- Email me a screenshot of the form content before you submit

I'll then make sure you get a key sent to you based on your screenshot information, also ask our website people if they can work out why your form submission isn't working as expected

**Comment by robinschneider** [comment]
> I've still not seen anything come through which looks like your name. Could you do the following?
> 
> * Fill out and submit the form one more time
> * Email me a screenshot of the form content before you submit
> 
> I'll then make sure you get a key sent to you based on your screenshot information, also ask our website people if they can work out why your form submission isn't working as expected

Thank you for your effort!
I send you an email with the subject `GitHub Issue 455 - Renovate Licence Key`.
