### ISSUE TITLE
Bad Credentials and Unable to read vulnerability information

### ISSUE THREAD

**Issue by vr** [mend/renovate-ce-ee#479]
Hello,

looks like my renovate is broken because it is unable to read vulnerability information :

`{"name":"renovate","hostname":"renovate-7bc759bf9-hqldx","pid":1237584,"level":40,"logContext":"2ff9bce955","repository":"sundayapp/enablers-chart-template","err":{"name":"HttpError","status":401,"response":{"url":"https://api.github.com/repos/renovatebot/osv-offline/releases","status":401,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","connection":"close","content-length":"80","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Thu, 21 Mar 2024 13:17:12 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"GitHub.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-media-type":"github.v3; format=json","x-github-request-id":"B863:D33F0:7B121C3:7BC6EDE:65FC3358","x-ratelimit-limit":"60","x-ratelimit-remaining":"0","x-ratelimit-reset":"1711027387","x-ratelimit-resource":"core","x-ratelimit-used":"99","x-xss-protection":"0"},"data":{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}},"request":{"method":"GET","url":"https://api.github.com/repos/renovatebot/osv-offline/releases","headers":{"accept":"application/vnd.github.v3+json","user-agent":"octokit-rest.js/20.0.2 octokit-core.js/5.1.0 Node.js/18.19.0 (linux; x64)","authorization":"***********"},"request":{"fetch":"[function]","hook":"[function]"}},"message":"Bad credentials","stack":"HttpError: Bad credentials\n at /usr/src/app/node_modules/renovate/node_modules/@octokit/request/dist-node/index.js:124:21\n at processTicksAndRejections (node:internal/process/task_queues:95:5)\n at tryDownloadDb (/usr/src/app/node_modules/renovate/node_modules/@renovatebot/osv-offline/dist/lib/download.js:46:26)\n at OsvOffline.initialize (/usr/src/app/node_modules/renovate/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:14:24)\n at Function.create (/usr/src/app/node_modules/renovate/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:26:9)\n at Vulnerabilities.initialize (/usr/src/app/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:56:23)\n at Function.create (/usr/src/app/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:61:5)\n at fetchVulnerabilities (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:177:31)\n at lookup (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:192:3)\n at extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:161:11)\n at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:62:9)\n at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:197:11)\n at start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:182:7)\n at /usr/src/app/node_modules/renovate/lib/renovate.ts:18:22"},"msg":"Unable to read vulnerability information","time":"2024-03-21T13:17:12.964Z","v":0}`

tracking down the issue i found https://github.com/renovatebot/renovate/pull/27361 which fixes https://github.com/renovatebot/renovate/discussions/26991 which looks the same as my issue.

Maybe @viceice can confirm this fix is not included in the v6.11.0 release of renovate-ce and maybe build a new one with it 🙏 ?

Thanks for your help !

**Comment by viceice** [comment]
I don't know. @nabeelsaabna can you check the renovate version?

**Comment by vr** [comment]
fixed, thx
