### ISSUE TITLE
Publish container for tag 6.11.1

### ISSUE THREAD

**Issue by tomkuipers** [mend/renovate-ce-ee#480]
Renovate tag `6.11.1` was released last week (see https://github.com/mend/renovate-ce-ee/releases/tag/mend-renovate-ce-6.11.1) but no container was published for this tag in the registry (https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce/versions?filters%5Bversion_type%5D=tagged).
Please publish containers for version `renovate-ce-6.11.1-full` and `renovate-ce-6.11.1`.

**Comment by nabeelsaabna** [comment]
Hi @tomkuipers 
release tags that contain only a version (e.g. `6.11.0`) are the ones that corresponds to publishing a new container image while
release tags like `renovate-ce-*` and `mend-renovate-enterprise-edition-*` are related to the helm charts releases
