### ISSUE TITLE
Report log level name in logs

### ISSUE THREAD

**Issue by morremeyer** [mend/renovate-ce-ee#485]
The log level is currently reported as `"level": 20` in the logs, which does not transport meaning.

I propose to add a `logLevel` field that corresponds to the levels in the application, e.g. `"logLevel": "error"` and so on.

**Comment by morremeyer** [comment]
I see where you're coming from and that definitely makes sense to me, too.

From my point of view: We're using a log aggregation system (loki in our case). For that, json as format is preferable since it is easy to parse - [a point that the documentation makes, too](https://github.com/mend/renovate-ce-ee/blob/a30c6de55d9b9d80dbf9611f438c5e45f2a46f6d/examples/docker-compose/renovate-ce-github.yml#L17).

However, when I tell colleagues to go to our logging system and then filter it, having to know the log levels instead of being able to see the usual string levels of error, warning, info, debug, trace makes it much harder to parse the logs.

That's why I suggested to _add_ this field instead of replacing the numeric one. 

My assumption here is also that there is an internal mapping of these levels since the `LOG_LEVEL` is specified as string, too.

**Comment by rarkins** [comment]
The additional benefit of numeric logging (which I'm pretty sure is "standard" for loggers) is that most log systems let you filter like e.g. `>30` to see both warnings and errors.

We would not want to do this by default, and also logging needs to be configured in env, so it would mean the introduction of a new env variable such as `LOG_JSON_LEVEL=true` (I can't think of a good one). If you're willing to experiment to see if it can be done easily/elegantly then you're welcome to go ahead and submit a PR if successful, but it's not Renovate CE specific - would need to be in Renovate CLI, so I'm going to close this here.
