### ISSUE TITLE
Runs on forks when not requested

### ISSUE THREAD

**Issue by TobiX** [mend/renovate-ce-ee#510]
It seems Renovate CE started running on forks some time ago. In the logs I can see
```
Enabling forkProcessing while in non-autodiscover mode
```
This sounds wrong to me...

**Comment by rarkins** [comment]
In GitHub, it should function like this:
- forkProcessing=enabled if "Selected repositories"
- forkProcessing=disabled if "All repositories"

For GitLab, where users "invite" the bot into repositories, I would think that forkProcessing=enabled would be expected by most users.

**Comment by TobiX** [comment]
Hmmm. In our internal GitLab environment teams usually invite the Renovate Bot into a group, not into individual projects. So it might happen that one forks a project from one group into another... But yeah, I see how both ways could be considered "correct". If I set `forkProcessing: "disabled"` as a global option, can users still override the setting in their repository? That might be a viable "workaround" for our internal GitLab...

**Comment by rarkins** [comment]
It might work to override it right now if you set it in env

**Comment by nabeelsaabna** [comment]
To minimize the configuration the servers "manages", should we create a new flag like `MEND_RENOVATE_FORKS_PROCESSING` for enabling the behavior of:

- `forkProcessing=enabled` if "Selected repositories"
- `forkProcessing=disabled` if "All repositories"
   
?

**Comment by rarkins** [comment]
Yes, we should allow users to manually control/override

**Comment by nabeelsaabna** [comment]
`MEND_RENOVATE_FORKS_PROCESSING` with valid values: `disabled | enabled | managed | <empty> ` :

### `disabled`
  -  `forkProcessing=disabled`

### `enabled`
   - `forkProcessing=enabled` 

### `managed`
 - Github:
   - `forkProcessing=enabled` if "Selected repositories"
   - `forkProcessing=disabled` if "All repositories"
  -  others:
     -  `forkProcessing=disabled`

### unset
 - `forkProcessing` will not be set by the server (Renovate CLI defaults to `forkProcessing=auto`)
 - default value

**Comment by rarkins** [comment]
I'm not sure it needs to be so complicated. What would you lose if you just let the user override RENOVATE_FORK_PROCESSING? i.e. if it's unset then you manage it, otherwise use what they ask for

**Comment by nabeelsaabna** [comment]
it's for the ease of use, allowing all options in one place instead of jumping from server to worker configurations.
`managed` for GitHub is the only option that needs a bit of work for making sure we have "all repositories" or "selected repositories" in relevant functions...

**Comment by nabeelsaabna** [comment]
released in `7.4.0`
