### ISSUE TITLE
Reporting apis for ce

### ISSUE THREAD

**Issue by NatMarchand** [mend/renovate-ce-ee#513]
In the release 7.2.0 https://github.com/mend/renovate-ce-ee/releases/tag/7.2.0 the following feature is reported:

> feat: enable reporting APIs for CE

However, in the doc https://github.com/mend/renovate-ce-ee/blob/7.2.0/docs/reporting-apis.md a different statement is reported.

>Reporting APIs are only supported for the following configuration:
>- Mend Renovate Enterprise Edition
>- Using PostgresDB for Renovate database

Which one is accurate?

**Comment by nabeelsaabna** [comment]
Hi @NatMarchand  the docs are out of date! 
Release notes are more accurate. Usually they are available before/same time of the docs (not after)

**Comment by nabeelsaabna** [comment]
https://github.com/mend/renovate-ce-ee/pull/514

**Comment by justo-mend** [comment]
Sorry for the delay in updating the docs. Great news - Reporting APIs are now available for Renovate CE!
However, some API data is for Enterprise customers only. Check the [Reporting API docs](https://github.com/mend/renovate-ce-ee/blob/main/docs/reporting-apis.md) for details.
