### ISSUE TITLE
Worker cleanup is inconsistent and breaks tools

### ISSUE THREAD

**Issue by alexymantha** [mend/renovate-ce-ee#516]
**Description**

When the worker cleanup runs, it will only partially delete tools which makes containerbase think the tool is still installed and make the execution fail.

When containerbase downloads a tool, it seems to keep the original date of when the files were created originally. Since the worker cleanup job compares the date of creation/modification of the files to the start date of the container, this means that some files do not get cleaned up properly because they were created before the start date of the container.

Below is an example with Node. 

**To Reproduce**

1. Enable worker cleanup every 5 minutes with: `mendRnvWorkerCleanup: 0/5 * * * *`
2. In the container, install Node 20.14.0: `install-tool node 20.14.0`
3. Wait for the cleanup to run.
4. Check the Node 20.14.0 directory. You will see that the node binary was deleted but everything else is still there.
5. If Renovate tries to use 20.14.0 it will fail because containerbase thinks Node 20.14.0 is already installed. See logs below.

**Result**

The container was started on Jun 5
```
$ ls -al /tmp/.ref.ec9d3ea776
-rw-r--r-- 1 ubuntu root 0 Jun  5 13:47 /tmp/.ref.ec9d3ea776
```
but the downloaded files are dated May 28
```
ls -al /opt/containerbase/tools/node/20.14.0/
total 660
drwxrwxr-x 7 ubuntu root    119 Jun  5 14:15 .
drwxrwxr-x 1 root   root     21 Jun  5 14:15 ..
-rw-r--r-- 1 ubuntu root 515592 May 28 04:46 CHANGELOG.md
-rw-r--r-- 1 ubuntu root 117411 May 28 04:46 LICENSE
-rw-r--r-- 1 ubuntu root  38676 May 28 04:46 README.md
drwxr-xr-x 2 ubuntu root     56 May 28 04:46 bin
drwxr-xr-x 2 ubuntu root     19 Jun  5 14:15 etc
drwxr-xr-x 3 ubuntu root     18 May 28 04:46 include
drwxr-xr-x 3 ubuntu root     26 May 28 04:46 lib
drwxr-xr-x 4 ubuntu root     28 May 28 04:46 share
```

The dating is also inconsistent, for example, `bin/` and the binaries in it are all dated May 28, but `etc/` and everything under it is dated June 5 at 14:15 which means everything under `etc/` gets deleted, but not the binaries which completely breaks the tools.

**Expected behavior**

The worker cleanup should delete all files **downloaded** after the start date of the container, regardless of when the files were created or modified.

**Version**

```shell
7.0.0
```

**Logs**

```
[10:19:08.544] INFO (15241): Installing tool node@20.14.0...
[10:19:08.551] INFO (15241): tool already installed
    tool: "node"
/usr/local/bin/node: line 6: /opt/containerbase/tools/node/20.14.0/bin/node: No such file or directory
[10:19:08.565] FATAL (15241): Command failed with exit code 127: node --version
[10:19:08.569] INFO (15241): Installed tool node with errors in 25ms.
```

**Comment by nabeelsaabna** [comment]
@alexymantha should be fixed in 7.4.0
