### ISSUE TITLE
mend.io github.com GITHUB_COM_TOKEN

### ISSUE THREAD

**Issue by bob-rohan** [mend/renovate-ce-ee#518]
Using `mend.io` , integrated with Bitbucket cloud at `bitbucket.org`, Renovate has correctly identified a `terraform` dependency via `.tool-versions` but cannot detect the latest version due to missing `GITHUB_COM_TOKEN`. 

`mend.io` environment variables supplied to job must be prefixed with `MEND_`. Can Renovate be configured to use a different environment variable name like `MEND_GITHUB_COM_TOKEN`?

**Comment by rarkins** [comment]
You should be able to fix this by configuring a hostRules entry with matchHost=github.com and a PAT as token.

@justo-mend do we have docs for this yet?

**Comment by rarkins** [comment]
FYI this is the mend app, not CE/EE

**Comment by bob-rohan** [comment]
I already tried with a host rule via mend.io, but in the job log I don't see that rule being integrated. I didn't know what to put for host type but it's mandatory.

```
description: github
Host Type: Go
hosturl: github.com
Username: bob-rohan
Secret type: Token
Secret: GITHUB_COM_TOKEN
```

**Comment by rarkins** [comment]
Mandatory host type is a mistake which is being fixed. Can you define it as a secret only and then reference it with your own hostRules in renovate config?

**Comment by bob-rohan** [comment]
Can you review the token syntax pls?

I have a mend app token GITHUB_COM_TOKEN, and hostRules in repo level renovate.json as 

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "hostRules": [
    {
      "matchHost": "github.com",
      "token": "GITHUB_COM_TOKEN"
    }
  ]
}
```

But got a 401 so guess the token is being treated as a literal not substituted out.
```
DEBUG: hostRules: authentication already set for api.github.com
DEBUG: POST https://api.github.com/graphql = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=182)
DEBUG: GitHub failure: Bad credentials
{
  "token": "***********"
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1717747868594,
      "socket": 1717747868594,
      "lookup": 1717747868595,
      "connect": 1717747868651,
      "secureConnect": 1717747868757,
      "upload": 1717747868757,
      "response": 1717747868776,
      "end": 1717747868776,
      "phases": {
        "wait": 0,
        "dns": 1,
        "tcp": 56,
        "tls": 106,
        "request": 0,
        "firstByte": 19,
        "download": 0,
        "total": 182
      }
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
```

**Comment by bob-rohan** [comment]
OK used "[encrypted](https://docs.renovatebot.com/getting-started/private-packages/#encrypting-secrets)" to success thanks. 

Global configuration
==========
It's not clear how I can mantain across many repositories without PR into each one. Is there a concept of global configuration I can leverage for this sort of thing please?
==========

Minor nit pick
==========
The wording of ["organisational"](https://app.renovatebot.com/encrypt) scoping was confusing as the source control provider is BitBucket, and the dependency is Github.

> Each secret you encrypt must be scoped to a GitHub org or repo and use of it will be restricted to those within the app.

I guessed that this was the name of the workspace in mend, which would be the name of the "organisation" on the source control system.
==========

**Comment by rarkins** [comment]
Encrypted secrets are being deprecated in favor of the web UI form so you will need to migrate them soon. If you've already configured a secret GITHUB_COM_TOKEN then the syntax for hostRules would be:

```
  "hostRules": [
    {
      "matchHost": "github.com",
      "token": "{{ secrets.GITHUB_COM_TOKEN }}"
    }
  ]
```

You can/should use a centralized config so that it can be configured centrally and not per-repo: https://docs.renovatebot.com/config-overview/#using-a-centralized-config

**Comment by bob-rohan** [comment]
Yep, both `{{ }}` and central config working as documented. Thanks @rarkins
