### ISSUE TITLE
docs(github): should the `MEND_RNV_CRON_JOB_SCHEDULER` and `MEND_RNV_CRON_APP_SYNC` have different formats?

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#522]
In https://github.com/mend/renovate-ce-ee/blob/b870a4aaae6b26abaff0f7e0a50fc0139e357320/docs/configure-renovate-ce-github.md?plain=1#L96-L98 we have differing forms of the `*` for the cron syntax - should it be escaped?

**Comment by PhilipAbed** [comment]
that is just a mistake i believe, 
default in code is `0 0,4,8,12,16,20 * * *`

**Comment by jamietanna** [comment]
Thanks @PhilipAbed - I'm happy to raise a PR if that's helpful?
