### ISSUE TITLE
Integration with Google Artifact Registry

### ISSUE THREAD

**Issue by ademariag** [mend/renovate-ce-ee#531]
Hello, 

my private pip (and docker) repositories are hosted using google artifact repository

for poetry, normally what I would need to do in order for it to be able to discover my packages is:
(https://cloud.google.com/artifact-registry/docs/python/authentication)

* have correct GCP credentials (usually through `GOOGLE_APPLICATION_CREDENTIALS`)
* install `keyrings.google-artifactregistry-auth`
* set this env variable: `PYTHON_KEYRING_BACKEND=keyrings.gauth.GooglePythonAuth`

Everything else is taken care by python.

Is this something that can be achieved with `renovate-ce`?

This would allow for self-hosted renovatebot to benefit from using https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity when running on GKE/Kubernetes, without the need to expose credentials

**Comment by PhilipAbed** [comment]
it's not related to `renovate-ce` or `renovate-ee` directly.
it's related to renovate open source configuration.

Connecting to private registries is usually found in renovate open source docs like: 
https://docs.renovatebot.com/docker/#google-container-registry-google-artifact-registry
or
https://docs.renovatebot.com/getting-started/private-packages/

if you are not sure how to do it after reading documentations, you might find/open a discussion about it in 
https://github.com/renovatebot/renovate/discussions
