### ISSUE TITLE
Clarification on the timezone for `MEND_RNV_CRON_JOB_SCHEDULER`

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#536]
I would assume that `MEND_RNV_CRON_JOB_SCHEDULER` follows the _local timezone_ that the container is running in, but it may also make sense to default to UTC - would you mind clarifying?

**Comment by PhilipAbed** [comment]
we are using 
https://www.npmjs.com/package/cron

and according to docs 

> timeZone: [OPTIONAL] - Sets the execution time zone. Default is local time. Check valid formats in the [Luxon documentation](https://github.com/moment/luxon/blob/master/docs/zones.md#specifying-a-zone).


so it should default to local timezone since we do not use this option.

**Comment by jamietanna** [comment]
Thanks @PhilipAbed!
