### ISSUE TITLE
Question about `MEND_RNV_SYNC_MODE`: how many repos should be considered for "orgs with very large numbers of repos" 

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#540]
I.e. would an organisation with ~3000 organisations want to tweak this? Or is this more for 10,000s of repos?

**Comment by nabeelsaabna** [comment]
I assume you mean ~3000 repos
Overall `MEND_RNV_SYNC_MODE=batch` is aimed to help lower the required memory by the server 
it's up to the user to decide if memory optimization is needed
