### ISSUE TITLE
Inconsistent changelogs/tags

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#541]
I've recently made an upgrade from v7.2.0 to v7.3.0, naturally using Renovate.

I noticed that the changelog shown on the Renovate PR is:

![2024-07-29-113932_906x589_scrot](https://github.com/user-attachments/assets/5afd5559-a1b9-426d-ae34-49e97db74bbb)

This links through to https://github.com/mend/renovate-ce-ee/compare/7.2.0...7.3.0 which seems reasonable.

However, it's not until the [next tagged release's changelog](https://github.com/mend/renovate-ce-ee/compare/7.3.0...7.4.0#diff-0e77e27f17233784552a4c31381765e6e6ce957487c75274f70924e318a61094R114-R115) that the deprecation of the `MEND_RNV_CRON_JOB_SCHEDULER` is seen, which ideally would be in the changelog for 7.3.0.

I also noticed that https://github.com/mend/renovate-ce-ee/releases/tag/mend-renovate-ce-7.6.0 has appeared, but there doesn't seem to be a Docker image pushed for this yet:

```sh
% crane ls ghcr.io/mend/renovate-ce
...
7.4.0-full
7.4.0
7.5.0-full
7.5.0
```

Is that intentional? If so, is it possible to clarify the usage of tags on the repo, and whether there's anything users should do to better follow the changelog that Renovate will surface for upgrades.

**Comment by jamietanna** [comment]
Looks like v7.6.0 _now_ exists, as I've just received a PR for it

**Comment by nabeelsaabna** [comment]
@jamietanna it might a manual error
Release notes + new tag are done manually and usually includes 2 sections: charts change and app changes

Tags in the repo:
`7.6.0`: version only, matching the docker-image version
`mend-renovate-enterprise-edition-1.6.1`: for the renovate-ee helm charts
`mend-renovate-ce-7.6.1`: for the renovate-ce helm charts
