### ISSUE TITLE
Unauthenticated GHE API call since v7.5.0 CE

### ISSUE THREAD

**Issue by simonkberg** [mend/renovate-ce-ee#544]
Hi, since v7.5.0 (CE) there appears to be an unauthenticated GHE API call executed during startup, fetching the bot user. Our GHE installation rate-limits all unauthenticated API calls to 0, which makes the request fail, and as a result renovate fails to startup.

Excerpt from logs:
```
GET https://xxx/api/v3/users/renovate[bot] = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=403 retryCount=0, duration=176)
GitHub failure: rate limit
Process will exit after 2 minutes
Failure initializing Renovate community edition - exiting...
```

Exception:
```
Error: external HTTP error occurred while initializing the platform
    at /usr/src/app/src/community.js:5:54636
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.mustInitialize (/usr/src/app/src/community.js:5:53490)
    at async Object.mustInitialize (/usr/src/app/src/community.js:5:57440)
    at async t.getPlatform (/usr/src/app/src/community.js:5:76400)
    at async /usr/src/app/src/community.js:5:112082
    at async /usr/src/app/src/community.js:5:111397
    at async /usr/src/app/src/community.js:5:111033
```

Prior versions work fine.

Is there a way to enforce that all GHE API calls are authenticated as the bot users, or alternatively provide a PAT for the initial call?

**Comment by paymand** [comment]
Same here, using renovate-ce, just updated to `7.6.1` and renovate doesn't start up. I'm getting this error:
```
hostRules: no authentication for api.github.com
```
@rarkins I know that this was a major update, so I'm wondering if we're missing something

**Comment by nabeelsaabna** [comment]
Indeed a new unauthenticated call added for [`GET /users/{username}`](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user) to retrieve The user ID that is public (we assumed only the email details required auth) 
Adding authentication to the API can be depended on a token that need to be provided via config

**Comment by paymand** [comment]
@nabeelsaabna so how to fix? something to do in our side or a fix in renovate is needed?

**Comment by nabeelsaabna** [comment]
working on a fix, we will add an option to provide the bot ID via config and skip the API call

**Comment by paymand** [comment]
@nabeelsaabna fyi, we are already setting the app ID using `mendRnvGithubAppId` if that's what you mean

**Comment by nabeelsaabna** [comment]
App ID is different from bot-user ID `https://api.github.com/users/${app-name}[bot]`

e.g. for the Renovate public APP calling this API https://api.github.com/users/renovate[bot] returns 
```
{
 "login": "renovate[bot]",
 "id": 29139614
 ...
``` 

We'll release the fix tomorrow with docs explaining how to find this value

**Comment by paymand** [comment]
@nabeelsaabna the bot id is also already include in `RENOVATE_GIT_AUTHOR` as a part of the email address.

**Comment by nabeelsaabna** [comment]
The `bot user ID` is actually needed for generating a `gitAuthor` full value to match the `platformCommit` value. 
In theory that can work for Renovate CE since its a single container solution, but for Renovate EE sever and worker are different containers for scalability and `RENOVATE_GIT_AUTHOR` will be a worker configuration while the `bot user ID` is needed as part of the server configuration.

**Comment by paymand** [comment]
Right, this means we do not need it for renovate ce. looks like some renovate ee feature that caused this bug in renovate ce. I just wanted to mention that we have that info already 👍

**Comment by paymand** [comment]
@nabeelsaabna thanks. shouldn't this be added to `renovate-ce` helm chart?
I create a little PR to add it: https://github.com/mend/renovate-ce-ee/pull/549

I didn't add it to `renovate-ee`, because I wasn't sure that was desired.

**Comment by paymand** [comment]
@nabeelsaabna Updated to v7.6.4 and added `mendRnvGithubBotUserId`. Renovate seems to run fine. Thanks 🙏 

Just a minor issue that I reported here: https://github.com/mend/renovate-ce-ee/issues/555
