### ISSUE TITLE
Environment Variable for writeDiscoveredRepos

### ISSUE THREAD

**Issue by nhandler** [mend/renovate-ce-ee#545]
Looking at https://docs.renovatebot.com/self-hosted-configuration/#writediscoveredrepos , the `writeDiscoveredRepos` configuration option can be set via the `--write-discovered-repos` CLI argument. However, there does not appear to be a way to specify it using an environment variable. Would it be possible to add support for a new `RENOVATE_WRITE_DISCOVERED_REPOS` environment variable?

**Comment by rarkins** [comment]
Wrong repo for this change. See https://github.com/renovatebot/renovate/pull/30487
