### ISSUE TITLE
Update `mendRnvCronJobScheduler` variable in helm chart

### ISSUE THREAD

**Issue by paymand** [mend/renovate-ce-ee#555]
Just updated to  renovate-ce `v7.6.4` and I'm getting this deprecation warning:

```
MEND_RNV_CRON_JOB_SCHEDULER is deprecated, please use MEND_RNV_CRON_JOB_SCHEDULER_ALL instead
```

but the only var defined in helm chart is `mendRnvCronJobScheduler` which is mapped to `MEND_RNV_CRON_JOB_SCHEDULER`.
This needs to be updated.

**Comment by nabeelsaabna** [comment]
Thanks for mentioning that. 
There are indeed a few missing configuration options in the helm charts

**Comment by nabeelsaabna** [comment]
done
