### ISSUE TITLE
Renovate not recognizing its own commits with `mendRnvGithubBotUserId`

### ISSUE THREAD

**Issue by quine** [mend/renovate-ce-ee#557]
Using Renovate-CE -- before #549 was introduced, the git author (on GHE server) was `renovate[bot] <renovate[bot]@users.noreply.github.mycompany.com>` -- but, when setting `MEND_RNV_GITHUB_BOT_USER_ID` / `mendRnvGithubBotUserId`, becomes `1234+renovate[bot] <renovate[bot]@users.noreply.github.mycompany.com>` (`1234` just being an example ID, of course).

After updating, this causes Renovate to _not_ recognize its own previous commits, leading to a ton of `Edited/Blocked Notification` comments on the PRs.

**Comment by nabeelsaabna** [comment]
@quine can you check any job/run configurations if it includes `gitIgnoredAuthors`

**Comment by quine** [comment]
@nabeelsaabna Yes, there _is_ one intentional entry in `gitIgnoredAuthors` in our shared/base config, as we have an in-house "bot" that occasionally makes comments on some PRs. However, that particular configuration has been there for a while and hasn't presented any issues.

**Comment by nabeelsaabna** [comment]
So in short this feature needs better documentation!
if you had `gitAuthor` set to `renovate[bot] <renovate[bot]@users.noreply.github.mycompany.com>` in the past
and now its updated to `renovate[bot] <1234+renovate[bot]@users.noreply.github.mycompany.com>`
the code will automatically include the old value in `gitIgnoredAuthors` to make sure the App recognizes it's PRs and Issues.
Solution: whenever you are overriding the value of `gitIgnoredAuthors` and need to include the old value in the list

**Comment by quine** [comment]
I never _manually_ set `gitAuthor`, though; that's the frustrating part about this change. It just _generally worked_ before.

**Comment by quine** [comment]
Is it possible to just override `gitAuthor` basically ignore what is in `mendRnvGithubBotUserId`? I'd like the `gitAuthor` to literally just remain what it's always been; having to manually set `gitIgnoredAuthors` to the previous git author -- simply because I already had something in there  -- is a frustrating kludge.

**Comment by rarkins** [comment]
You don't have to manually set ignored authors, but you chose to (in your shared config). If you do that then you need to include the one suggested by @nabeelsaabna. If your config had left ignored authors empty then everything would have worked.

**Comment by quine** [comment]
Ah, yes, thank you. I see it in logs where it _was_, in fact, setting `gitIgnoredAuthors` to "itself" 🙃 . After manually putting the "old" git author into our base config, that resolved it.
