### ISSUE TITLE
Renovate regex_filter option

### ISSUE THREAD

**Issue by githubcdr** [mend/renovate-ce-ee#570]
Hi,

When starting Renovatebot-ce edition I notice that renovate detects two regex_filters, where I have configured only one via ENV.

MEND_RNV_AUTODISCOVER_FILTER=GrQ/*

```
 INFO: validating regex filter
       "filter": ["GrQ/*"]
 INFO: validating regex filter
       "filter": ["/dev/**"]
```

I don't understand this and I think this might be a bug? Where does "/dev/**" come from and can I remove it somewhere?

**Comment by rarkins** [comment]
You need debug logs

**Comment by Gabriel-Ladzaretti** [comment]
`["/dev/**"]` is the regex filter for `MEND_RNV_DISK_USAGE_FILTER`. you are all good :)

**Comment by Gabriel-Ladzaretti** [comment]
regardless, checkout your `Resolved configuration` log message to see exactly what is what.
