### ISSUE TITLE
Inconsistent ENV var (Forks Processing)

### ISSUE THREAD

**Issue by kiliantyler** [mend/renovate-ce-ee#583]
This env var was release just a few months ago with [v7.4.0](https://github.com/mend/renovate-ce-ee/pull/530): [`MEND_RENOVATE_FORKS_PROCESSING`](https://github.com/mend/renovate-ce-ee/issues/510)

My issue isn't a "real" one just, why is it not following the seemingly established pattern of `MEND_RNV_<VAR>`?

Looking at the [documentation](https://github.com/mend/renovate-ce-ee/blob/main/docs/configuration-options.md) there are 67 hits (some are duplicates) for `MEND_RNV_` and only 1 for `MEND_RENOVATE_`

In the [Self-Hosted configuration](https://docs.renovatebot.com/self-hosted-configuration/) there are Env vars that are mostly `RENOVATE_` and just a few of the `MEND_RNV_` that carry over, but 0 others that are `MEND_RENOVATE_`.

As a matter of fact searching the doc site for `MEND_RENOVATE` returns 0 results whereas both `RENOVATE_` and `MEND_RNV_` return pages.

Just seems out of place. Some hybrid between the "user configs" `RENOVATE_` and the "admin configs" `MEND_RNV_`

Since it is already released I imagine it has to continue to be supported for a while, but allowing it to be `MEND_RNV_FORKS_PROCESSING` would be nice

**Comment by Gabriel-Ladzaretti** [comment]
@kiliantyler, thank you for taking the time to raise this issue. it was actually a typo in our docs.
