### ISSUE TITLE
gitIgnoredAuthors in config.js is being overriden by RENOVATE_CONFIG environment variable

### ISSUE THREAD

**Issue by 613andred** [mend/renovate-ce-ee#594]
Hello Renovate team,

The `gitIgnoredAuthors` does not have the value we are expecting.

We have configured `gitIgnoredAuthors` in `config.js` via the helm `renovate.config` value.

Because `RENOVATE_CONFIG` has set `gitIgnoredAuthors` to the legacy `gitAuthor` value it is overriding `config.js`

I tried overriding the value in `RENOVATE_CONFIG` by setting `RENOVATE_GIT_IGNORED_AUTHORS=""` but it had no effect (I based this on the proposed workaround in a similar issue https://github.com/mend/renovate-ce-ee/issues/371#issuecomment-1766211328).

I have a suspicion that this bug was introduced in [7.5.0](https://github.com/mend/renovate-ce-ee/releases/tag/7.5.0) with change
> fix: update git author to match the app author
>   * from `app-name[bot]@users.noreply.github.com` to` app-name[bot] <405054+app-name[bot]@users.noreply.github.com>`
>   * note: old value of git author will be set in the `gitIgnoredAuthors` for backward comparability

We are running renovate CE 8.4.0.

**Comment by rarkins** [comment]
Are you trying to set it to an empty string? If so why?

**Comment by 613andred** [comment]
> Are you trying to set it to an empty string? If so why?
Yes, I was trying that as a way to unset the value in `RENOVATE_CONFIG` so that the value in `config.json` would get used in the final config.

I can confirm that if I set a value ex. `RENOVATE_GIT_IGNORED_AUTHORS="app-name[bot]@users.noreply.github.com"` it does get set into `RENOVATE_CONFIG`.

What I see in the debug logs (when not setting RENOVATE_GIT_IGNORED_AUTHORS) is:

```
DEBUG: File config
	"config": {
		"gitIgnoredAuthors": [
			"my-bot[bot]@users.noreply.github.com",
			"my-bot2[bot]@users.noreply.github.com"
		]
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "gitIgnoredAuthors": ["app-name[bot]@users.noreply.github.com"],
DEBUG: Combined config
       "config": {
         "gitIgnoredAuthors": ["app-name[bot]@users.noreply.github.com"],
```

What I am expecting is `Combined config` to show the `gitIgnoredAuthors` from `File config`.

**Comment by rarkins** [comment]
That won't be possible because env takes higher priory than file config. To override the default you'll need to use env. It's not a bug, so closing now.

**Comment by 613andred** [comment]
I am not setting the environment variable, renovate CE is setting it by default.

Is the expected behaviour that we cannot set `gitIgnoredAuthors` in `config.js`? this is how we had it configured previously.

If you need me to I can confirm by spinning up and older version and confirming that it used to work this way.

**Comment by rarkins** [comment]
It's expected. You're welcome to submit a PR clarifying as such in the docs in this repo.

**Comment by lindeskar** [comment]
For anyone arriving here from the "Edited/Blocked notification on every PR" symptom: this precedence behavior is the reason `gitIgnoredAuthors` set in `config.js` (or a `globalExtends` preset) silently does nothing once `mendRnvGithubBotUserId` is set — CE injects its own `gitIgnoredAuthors` at the env layer, which wins (arrays replace, they don't merge).

The only lever that takes effect is the `RENOVATE_GIT_IGNORED_AUTHORS` env var, and you have to include the legacy Renovate author yourself alongside any custom ones (e.g. a bot that commits generated files back onto Renovate PRs). See #741.
