### ISSUE TITLE
Github webhooks received but never doing anything

### ISSUE THREAD

**Issue by georgekaz** [mend/renovate-ce-ee#598]
Hi.
I'm using the release 8.4.0 CE deployed in my cluster via helm and my repos are in Github.com. I chose CE over the OSS version primarily because of the webhook support, but it seems like they don't do anything. Documentation on the webhooks is scarce/non-existent, so as they are closed source they are hard to understand.

An area I thought they would be used is for triggering a rebase, which you can allegedly do via checking the box in the PR description or by adding a specific label to the PR. However, when I do either of these actions, although I see the webhook being sent and I have the trace of it being received, it never does anything. It always says `WARN: GitHub webhook request is missing a required signature` or
```
DEBUG: event is missing installation details - ignoring event
       "event": "pull_request",
       "action": "labeled"
DEBUG: Discarding webhook event - no action required
```
I've attached a couple of files containing logs.

I'm using Github organization level webhooks but have also tested this with repo level webhooks.

Our config schedules all PR creation and rebasing outside of working hours. I thought you could force a rebase at any other time using these methods, am I wrong?

[add-pr-label.log](https://github.com/user-attachments/files/17590311/add-pr-label.log)
[check-box-in-description.log](https://github.com/user-attachments/files/17590312/check-box-in-description.log)

Thanks

**Comment by rarkins** [comment]
> I'm using Github organization level webhooks but have also tested this with repo level webhooks.

This is not how you should configure webhooks. You should set up as a GitHub app which will then take care of webhooks per-repo automatically.

Follow these instructions: https://github.com/mend/renovate-ce-ee/blob/main/docs/setup-for-github.md#create-and-configure-the-github-app-bot

**Comment by georgekaz** [comment]
Thanks @rarkins . I had already configured that on my app as per those docs when I first created it but it wasn't doing anything. It seems like I hadn't set the secret value (because I'd not yet deployed Renovate) and that without the secret it the webhook wasn't coming.

The good news is, it's now sending the request. The bad news is that although it says `DEBUG: Done processing task` and outputs loads of trace logs that appear to be doing something, it doesn't actually rebase the branch and it doesn't untick the box in the PR description.

```
TRACE: Processed GitHub webhook event
       "event": {
         "organizationName": "xxxxxxxx",
         "installationId": xxxxxxxx,
         "repositories": ["xxx"],
         "action": "enqueue",
         "reason": "rebase-request"
       }
DEBUG: Webhook analyzed
       "processedWebhookEvent": {
         "organizationName": "xxxxxxxx",
         "installationId": xxxxxxxx,
         "repositories": ["xxx"],
         "action": "enqueue",
         "reason": "rebase-request",
         "type": "external"
       }
DEBUG: Processing new task
       "task": {
         "id": "fcfdbd8a-dd6b-5876-8d8b-d2805178b661",
         "reason": "rebase-request",
         "priority": 120,
         "organizationName": "xxxxxxxx",
         "installationId": xxxxxxxx,
         "action": "enqueue",
         "addedAt": "2024-11-01 09:17:32",
         "repositories": ["xxx"],
         "attempts": 1,
         "type": "external"
       }
DEBUG: Done processing task
```

After loads of trace logs I do see the following error message but I don't know that it's related
```
Error: write ENOBUFS
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writevGeneric (node:internal/stream_base_commons:144:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._writev (node:net:961:8)
    at doWrite (node:internal/streams/writable:594:12)
    at clearBuffer (node:internal/streams/writable:773:5)
    at onwrite (node:internal/streams/writable:651:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:107:10)
ERROR: renovate cli error (repository=xxx)
       "err": {
         "cmd": "/bin/sh -c /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js",
         "stderr": "",
         "stdout": "",
         "options": {
           "encoding": "utf-8",
           "env": [
 				(LOTS OF ENV VARS HERE)
           ],
           "maxBuffer": null,
           "stdio": "inherit",
           "timeout": 3600000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js\n",
         "stack": "ExecError: Command failed: /usr/bin/node_default /usr/src/app/node_modules/renovate/dist/renovate.js\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/exec/common.js:88:24)\n    at ChildProcess.emit (node:events:531:35)\n    at ChildProcess.emit (node:domain:488:12)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)"
       }
DEBUG: Renovate job finished (repository=xxx)
       "status": "cli-error"
```

**Comment by rarkins** [comment]
Let's close this issue, because the original topic is resolved. The purpose of the webhook receiver is to receive webhooks and add a job to the queue.

**Comment by rarkins** [comment]
Actually, please don't create Issues anymore - create Discussions instead.

**Comment by georgekaz** [comment]
ok, no problem, thanks. I managed to get it to work once after reducing the log level to debug from trace, so maybe the verbose logging was actually causing the problem.
