### ISSUE TITLE
Explicitly ignoring repositories when using a GitHub App with `install on all repositories`

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-ce-ee#608]
When setting up a GitHub App with `install on all repositories`, we would like to exclude specific repositories from being processed.

For instance, there are some repositories that we want to only enable for the development GitHub App, which is installed with `install on selected repositories`.

However, the production GitHub App can access + process all repos, so there's then a little bit of "fighting" between bots

This configuration would allow us to provide an exclusion of i.e. `org/repo,another-org/repo` etc

Each GitHub App is configured on a separate Mend Renovate CE

**Comment by jamietanna** [comment]
This could be related to https://github.com/mend/renovate-ce-ee/issues/520 but is a slightly different view - we've got an active repo that we want to snooze/disable one of our GitHub Apps on

**Comment by rarkins** [comment]
Does `autodiscoverFilter` work?

**Comment by jamietanna** [comment]
We'd not given that a go - my understanding of [`autodiscoverfilter`](https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter) was that when there are many negations it could get a little awkward

i.e. would it be:

```json
{
  "autodiscoverFilter": [
		"!/org\/repo/",
		"!/another-org\/repo/"
	]
}
```

To allow us to exclude those two repos from any auto-discovered repos?

**Comment by jamietanna** [comment]
I notice that [`autodiscoverfilter`](https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter) indicates multiple negations should  be avoided?

Coming back to this - looking at this we'd need to use `MEND_RNV_AUTODISCOVER_FILTER`, preferably with only one regex that could negate any pattern(s) we need, in a single regex?

**Comment by jamietanna** [comment]
Closing as Rhys' original comment is correct - using `MEND_RNV_AUTODISCOVER_FILTER` with a single regex is the option here - i.e.

```
MEND_RNV_AUTODISCOVER_FILTER="!/(org\/repo|another-org\/repo)/"
```

We've set up a small test harness for validating this, to catch any issues in the future, which calls in to i.e.

```javascript
  const autodiscover = require('renovate/dist/workers/global/autodiscover')
// ...
  const actual = autodiscover.applyFilters(repos, [filter])
// ...
```
