### ISSUE TITLE
Renovate CE 9.0 uses different user ID

### ISSUE THREAD

**Issue by thegcat** [mend/renovate-ce-ee#619]
The [docs](https://github.com/mend/renovate-ce-ee/blob/main/docs/configuration-options.md?plain=1#L90) mention files mounted to the docker container need to be owned by user `1000:1000`, it seems that the switch to Ubuntu 24.04/Renovate CE 9.0 changed this to `12021:12021`.

**Comment by Gabriel-Ladzaretti** [comment]
thanks a lot for pointing this out, addressed in #620.

**Comment by thegcat** [comment]
Thank you for taking care of this. Unfortunately I forgot to mention that the username also changed, it used to be `node` and is now `ubuntu`:

```
ubuntu@b79670dc882d:/usr/src/app$ id
uid=12021(ubuntu) gid=0(root) groups=0(root),999(docker),12021(ubuntu)
```

Sorry for the hassle.

**Comment by justo-mend** [comment]
Thanks again for helping us find and fix this.
I've pushed the update. Can you please check if it's correct and comment or close this issue?
Your help is much appreciated.

**Comment by thegcat** [comment]
I don't see anything that I would think would be false. Thank you for caring for the documentation too <3
